const C=window.CONVERGENCE_CONFIG,$=id=>document.getElementById(id),state=()=>localStorage.getItem("convergenceState")||C.defaultState;
const get=(k,d)=>localStorage.getItem(k)||d, norm=s=>(s||"").trim().replace(/\s+/g," ").toUpperCase(), show=(id,on=1)=>$(id)?.classList.toggle("hidden",!on), text=(id,v)=>{$(id)&&($(id).textContent=v)};
function clear(){["message","codeBox","cascade","resolved"].forEach(x=>show(x,0));document.body.classList.remove("cascade")}
function base(){clear();text("eyebrow","INTERDIMENSIONAL EVENT ACTIVE");text("title","WELCOME TO THE CONVERGENCE");text("subtitle","SPACETIME SYNCHRONIZATION UNDER CONTROL");text("conv","STABLE");text("archive","MONITORING");text("integrity","100.00%");text("anchor","STANDBY");text("frame","LOCKED")}
function render(){base();let s=state();
if(s==="PHASE1"){text("title","ARCHIVE ANOMALY DETECTED");text("subtitle","PRE-CONVERGENCE MEMORY RECORDS REQUIRE RECONSTRUCTION");text("archive","CORRUPTED");text("integrity","96.41%");show("message");$("message").innerHTML="ARCHIVE RECONSTRUCTION ACTIVE<br><small>Recover and validate corrupted Memory Records.</small>";show("codeBox");text("codeLabel","ENTER ARCHIVE RECONSTRUCTION CODE")}
if(s==="PHASE1_COMPLETE"){text("title","ARCHIVE RESTORED");text("subtitle","FOUR COMPATIBLE TIMELINES DETECTED");text("archive","VERIFIED");text("anchor","PENDING");show("message");$("message").innerHTML="ASTRA &nbsp; NOVA &nbsp; VEGA &nbsp; UMBRA<br><small>ANCHOR PROTOCOL awaiting authorization.</small>"}
if(s==="PHASE2"){text("title","ANCHOR PROTOCOL ACTIVE");text("subtitle","IDENTIFY A STABLE REFERENCE TIMELINE");text("archive","VERIFIED");text("anchor","ANALYZING");show("message");$("message").innerHTML="ASTRA &nbsp; NOVA &nbsp; VEGA &nbsp; UMBRA";show("codeBox");text("codeLabel","ENTER ANCHOR PROTOCOL CODE")}
if(s==="CLEARED"||s==="PROVISIONAL"){text("title","CONVERGENCE STABLE");text("subtitle",s==="PROVISIONAL"?"PROVISIONAL PRIMARY ANCHOR ESTABLISHED":"PRIMARY ANCHOR ESTABLISHED");text("archive","VERIFIED");text("anchor",s==="PROVISIONAL"?"PROVISIONAL":"ACTIVE");text("frame","NOVA");show("message");$("message").innerHTML=(s==="PROVISIONAL"?"AUTOMATIC STABILIZATION COMPLETE":"CASE CLOSED")+"<br><small>All registered Variants cleared.</small>"}
if(s==="CASCADE"){document.body.classList.add("cascade");text("eyebrow","EMERGENCY PROTOCOL ACTIVE");text("title","CASCADE FAILURE");text("subtitle","PRIMARY ANCHOR INSTABILITY DETECTED");text("conv","CRITICAL");text("archive","EMERGENCY");text("anchor","FAILED");text("frame","UNSTABLE");show("cascade");startTimer()}
if(s==="RESOLVED"){text("eyebrow","CONVERGENCE RESTORED");text("title","CASCADE TERMINATED");text("subtitle","ALL ACTIVE TIMELINES SYNCHRONIZED");text("anchor","DISTRIBUTED");text("frame","ALL TIMELINES");show("resolved")}}
function validate(){let s=state(),v=norm($("code").value),ok=s==="PHASE1"?norm(get("phase1Code",C.phase1Code)):norm(get("phase2Code",C.phase2Code));if(v===ok){localStorage.setItem("convergenceState",s==="PHASE1"?"PHASE1_COMPLETE":"CLEARED");text("feedback","CODE ACCEPTED.");setTimeout(render,400)}else text("feedback","INVALID CODE.")}
$("submitCode").onclick=validate;$("code").addEventListener("keydown",e=>e.key==="Enter"&&validate());
document.querySelectorAll("[data-t]").forEach(b=>b.onclick=()=>text("overrideFeedback",b.dataset.t+" SELECTED — SINGLE-TIMELINE STABILIZATION FAILED."));
$("overrideBtn").onclick=()=>show("overrideBox",$("overrideBox").classList.contains("hidden"));
function exec(){if(norm($("override").value)===norm(get("finalCommand",C.finalCommand))){text("overrideFeedback","COMMAND ACCEPTED — RELEASING PRIMARY ANCHOR...");setTimeout(()=>{localStorage.setItem("convergenceState","RESOLVED");render()},1200)}else text("overrideFeedback","COMMAND REJECTED — CONFIGURATION UNSTABLE.")}
$("exec").onclick=exec;$("override").addEventListener("keydown",e=>e.key==="Enter"&&exec());
let h;function startTimer(){clearInterval(h);let mins=Number(get("timerMinutes",C.cascadeMinutes)),start=Number(localStorage.getItem("cascadeStart"))||Date.now();localStorage.setItem("cascadeStart",start);h=setInterval(()=>{let r=Math.max(0,mins*60000-(Date.now()-start)),s=Math.ceil(r/1000);text("timer",String(Math.floor(s/60)).padStart(2,"0")+":"+String(s%60).padStart(2,"0"));text("integrity",Math.max(12,71.32-(1-r/(mins*60000))*55).toFixed(2)+"%")},250)}
setInterval(()=>text("clock",new Date().toLocaleTimeString("it-IT",{hour12:false})),1000);setInterval(()=>{text("drift","+"+(0.002+Math.random()*.003).toFixed(4)+"%");text("sys","CX-"+Math.floor(1000+Math.random()*9000))},5000);window.addEventListener("storage",render);render();